[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Optional: for USB connection on some boards
; upload_port = COM3
; monitor_port = COM3
